# Site settings
title:          Daniel Tomé | Blog
baseurl:        ""
url:            "https://danitome24.github.io"
description:    "El blog personal de Daniel Tomé"

# Author
author:
  name:         Daniel Tomé Fernández
  url:          https://danitome24.githubpages.io
  email:        danieltomefer@gmail.com

# Twitter
twitter_username: danitome24

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

font-awesome:
  assets: true
# Gems
plugins:
  - jekyll-paginate
  #- jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
