version: '3'

services:
  danitome24.github.io:
    container_name: danitome24.github.io
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
