version: '3'

services:
  blog_mailhog:
    build: .
    container_name: blog_mailhog
    ports:
      - 8000:80

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
